<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Nuestras Catequesis</title>

<link rel="stylesheet" href="../css/catequesis.css"> 

    <!--BOOTSTRAP-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

<!--CDN jQuery-->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"
    integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    
</head>
<body>

<!--BOOTSTRAP-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>

<header>

    <nav>
        <a href="../index.html">Inicio</a>
        <a href="../intranet/catequesis.html">Catequesis</a>
        <!--<a href="#">Instalaciones</a>
        <a href="#">Historia</a>-->
        <a href="../intranet/grupos.html">Grupos Parroquiales</a>
    </nav>


    <section class="textos-header">
        <h1>Libres para Liberar</h1>
        <h2>No hay mejor maestro que Jesús</h2>
    </section>

    <!--Onda descargada de internet-->
    <div class="wave">
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M-5.41,68.39 C148.08,144.18 275.05,95.96 510.95,57.57 L500.00,149.60 L-0.00,149.60 Z"
                    style="stroke: none; fill:white;"></path>
            </svg></div>
    </div>


</header>

<main>

<section class="c_especial" id="c1">
    <h2 class="titulo">Catequesis Especial</h2>
    
<div class="container">
    <div class="row">
        <p class="descripcion">El Sacramento de la Eucaristía conocido popularmente como Primera Comunión es un Sacramento que nos une a Cristo y
            nos
            hace partícipes de su Cuerpo y de su Sangre para formar un solo cuerpo. La Eucaristía es "fuente y vida de toda la
            vida
            cristiana" ya que contiene todo bien espiritual de la Iglesia, es decir, Cristo mismo, nuestra Pascua.
            La Eucaristía significa y realiza la comunión de vida con Dios y la unidad del Pueblo de Dios por las que la Iglesia
            es
            ella misma.</p>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="contenido_texto">
                <h3>Visión</h3>
                <p>Suscitar la proclamación de las maravillas que Dios ha realizado en favor de los hombres mediante la celebración
                    Litúrgica, dónde estos acontecimientos se hacen presentes y actuales.</p>
                <h3>Misión</h3>
                <p>Conducir al cristiano a recibir el Cuerpo y la Sangre de Cristo para cumplir el mandato que el Señor nos entregó
                    en el
                    memorial de su sacrificio como acción de gracias, alabanza al Padre y como presencia de Cristo por el poder de
                    su
                    Palabra y de su Espíritu.</p>
            
            </div>


        </div>
        <div class="col-md-6">
<div class="carrusel">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-bs-interval="5000">
        <ol class="carousel-indicators">
            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="../img/1.png" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="../img/2.png" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="../img/3.png" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>

        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>

        </a>
    </div>
</div>
        </div>

        <div class="row"><a href="#" class="enlace-boton"><button>Requisitos de Inscripción</button></a></div>

    </div>
</div>

</section>

<section class="c_catecumenado par" id="c2">
    <h2 class="titulo">Catequesis de Catecumenado</h2>

    <div class="container">
        <div class="row">
            <p class="descripcion">El Sacramento de la Eucaristía conocido popularmente como Primera Comunión es un
                Sacramento que nos une a Cristo y
                nos
                hace partícipes de su Cuerpo y de su Sangre para formar un solo cuerpo. La Eucaristía es "fuente y vida
                de toda la
                vida
                cristiana" ya que contiene todo bien espiritual de la Iglesia, es decir, Cristo mismo, nuestra Pascua.
                La Eucaristía significa y realiza la comunión de vida con Dios y la unidad del Pueblo de Dios por las
                que la Iglesia
                es
                ella misma.</p>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="carrusel">
                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel"
                        data-bs-interval="5000">
                        <ol class="carousel-indicators">
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="../img/1.png" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="../img/2.png" alt="Second slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="../img/3.png" alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                            data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>

                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                            data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>

                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="contenido_texto">
                    <h3>Visión</h3>
                    <p>Suscitar la proclamación de las maravillas que Dios ha realizado en favor de los hombres mediante
                        la celebración
                        Litúrgica, dónde estos acontecimientos se hacen presentes y actuales.</p>
                    <h3>Misión</h3>
                    <p>Conducir al cristiano a recibir el Cuerpo y la Sangre de Cristo para cumplir el mandato que el
                        Señor nos entregó en el
                        memorial de su sacrificio como acción de gracias, alabanza al Padre y como presencia de Cristo
                        por el poder de su
                        Palabra y de su Espíritu.</p>

                </div>
            </div>

            <div class="row"><a href="#" class="enlace-boton"><button>Requisitos de Inscripción</button></a></div>

        </div>
    </div>

</section>

<section class="c_comunion" id="c3">
    <h2 class="titulo">Catequesis de Primera Comunión</h2>

    <div class="container">
        <div class="row">
            <p class="descripcion">El Sacramento de la Eucaristía conocido popularmente como Primera Comunión es un
                Sacramento que nos une a Cristo y
                nos
                hace partícipes de su Cuerpo y de su Sangre para formar un solo cuerpo. La Eucaristía es "fuente y vida
                de toda la
                vida
                cristiana" ya que contiene todo bien espiritual de la Iglesia, es decir, Cristo mismo, nuestra Pascua.
                La Eucaristía significa y realiza la comunión de vida con Dios y la unidad del Pueblo de Dios por las
                que la Iglesia
                es
                ella misma.</p>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="contenido_texto">
                    <h3>Visión</h3>
                    <p>Suscitar la proclamación de las maravillas que Dios ha realizado en favor de los hombres mediante
                        la celebración
                        Litúrgica, dónde estos acontecimientos se hacen presentes y actuales.</p>
                    <h3>Misión</h3>
                    <p>Conducir al cristiano a recibir el Cuerpo y la Sangre de Cristo para cumplir el mandato que el
                        Señor nos entregó
                        en el
                        memorial de su sacrificio como acción de gracias, alabanza al Padre y como presencia de Cristo
                        por el poder de
                        su
                        Palabra y de su Espíritu.</p>

                </div>


            </div>
            <div class="col-md-6">
                <div class="carrusel">
                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel"
                        data-bs-interval="5000">
                        <ol class="carousel-indicators">
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="../img/1.png" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="../img/2.png" alt="Second slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="../img/3.png" alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                            data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>

                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                            data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>

                        </a>
                    </div>
                </div>
            </div>

            <div class="row"><a href="#" class="enlace-boton"><button>Requisitos de Inscripción</button></a></div>

        </div>
    </div>

</section>

<section class="c_confirmacion par" id="c4">
    <h2 class="titulo">Catequesis de Confirmación</h2>

    <div class="container">
        <div class="row">
            <p class="descripcion">El Sacramento de la Eucaristía conocido popularmente como Primera Comunión es un
                Sacramento que nos une a Cristo y
                nos
                hace partícipes de su Cuerpo y de su Sangre para formar un solo cuerpo. La Eucaristía es "fuente y vida
                de toda la
                vida
                cristiana" ya que contiene todo bien espiritual de la Iglesia, es decir, Cristo mismo, nuestra Pascua.
                La Eucaristía significa y realiza la comunión de vida con Dios y la unidad del Pueblo de Dios por las
                que la Iglesia
                es
                ella misma.</p>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="carrusel">
                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel"
                        data-bs-interval="5000">
                        <ol class="carousel-indicators">
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
                            <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="../img/1.png" alt="First slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="../img/2.png" alt="Second slide">
                            </div>
                            <div class="carousel-item">
                                <img class="d-block w-100" src="../img/3.png" alt="Third slide">
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                            data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>

                        </a>
                        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                            data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>

                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="contenido_texto">
                    <h3>Visión</h3>
                    <p>Suscitar la proclamación de las maravillas que Dios ha realizado en favor de los hombres mediante
                        la celebración
                        Litúrgica, dónde estos acontecimientos se hacen presentes y actuales.</p>
                    <h3>Misión</h3>
                    <p>Conducir al cristiano a recibir el Cuerpo y la Sangre de Cristo para cumplir el mandato que el
                        Señor nos entregó en el
                        memorial de su sacrificio como acción de gracias, alabanza al Padre y como presencia de Cristo
                        por el poder de su
                        Palabra y de su Espíritu.</p>

                </div>
            </div>

            <div class="row"><a href="#" class="enlace-boton"><button>Requisitos de Inscripción</button></a></div>

        </div>
    </div>

</section>

<section class="sobre-nosotros">            
            <div class="contenedor-sobre-nosotros">
                <div class="container">
                    <div class="row">
                        <h2 class="titulo">Los Coordinadores</h2>
        
                        <div class="col-md-3">                            
                            <img src="../img/fondo1.jpg" class="imagen-grupos">
                            <h3><span>Paty Colín</span></h3>
                        </div>
        
                        <div class="col-md-9">
                            <div class="contenido-texto">
                                <h3>Primera Comunión</h3>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique incidunt beatae corporis
                                    fuga assumenda
                                    aliquam maiores, esse excepturi laboriosam veritatis obcaecati reprehenderit voluptas hic
                                    eaque, earum dicta
                                    placeat. Odio, cupiditate.</p>
        
                            </div>
                        </div>
                    </div>

                    <div class="row">
                    
                        <div class="col-md-3">
                            <img src="../img/fondo1.jpg" class="imagen-grupos">
                            <h3><span>Paty Colín</span></h3>
                        </div>
                    
                        <div class="col-md-9">
                            <div class="contenido-texto">
                                <h3>Catequesis Especial</h3>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique incidunt beatae corporis
                                    fuga assumenda
                                    aliquam maiores, esse excepturi laboriosam veritatis obcaecati reprehenderit voluptas hic
                                    eaque, earum dicta
                                    placeat. Odio, cupiditate.</p>
                    
                            </div>
                        </div>
                    </div>

                    <div class="row">
                    
                        <div class="col-md-3">
                            <img src="../img/fondo1.jpg" class="imagen-grupos">
                            <h3><span>Paty Colín</span></h3>
                        </div>
                    
                        <div class="col-md-9">
                            <div class="contenido-texto">
                                <h3>Confirmación</h3>
                                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique incidunt beatae corporis
                                    fuga assumenda
                                    aliquam maiores, esse excepturi laboriosam veritatis obcaecati reprehenderit voluptas hic
                                    eaque, earum dicta
                                    placeat. Odio, cupiditate.</p>
                    
                            </div>
                        </div>
                    </div>

                </div>
                
            </div>
        
            </div>
</section>

<section class="parroco-vicario contenedor">
            
            <div class="cards-parroco">
        
                <div class="container">
                    <div class="row">
                        <div class="card-parroco">
                            
                            <div class="col-md-12">
                                <div class="contenido-texto-card">
                                    <form class="form" action="">
                                        <h4>Registro a Curso</h4>
                                        <input class="controles" type="text" name="nombres" id="nombres" placeholder="Ingrese su nombre">
                                        <input class="controles" type="text" name="apellido" id="apellido" placeholder="Ingrese su apellido">
                                        <input class="controles" type="email" name="correo" id="correo" placeholder="Ingrese su correo">
                                        <br>
                                        <label for="f" class="form-label">Fecha de Nacimiento</label>
                                        <input class="controles" type="date" class="form-control" id="f" name="nacimiento">
                                        
                                        <br>
                                        <select class="controles"name="catequesis" id="">
                                            <option >Selecciona el curso a inscribir</option>
                                            <option value="curso1">Primera Comunión</option>
                                            <option value="curso2">Confirmación</option>
                                            <option value="curso3">Catequesis Especial</option>
                                            <option value="curso4">Catecumenado</option>
                                        </select>
                                        <br>
                                        <label class="form-label" for="a">Agregue 1 solo PDF de sus documentos</label>
                                        <input class="controles" type="file" class="form-control" id="a" name="acta">
                                        <br>                                        
                                        <input type="submit" value="enviar" class="btn btn-primary">                                      
                                        <input type="reset" value="borrar" class="btn btn-primary">
                                        <p>Estoy de acuerdo con <a href="#">Términos y condiciones</a></p>
                                        <br>
                                    </form>
                                </div>
                            </div>
                        </div>
        
                    </div>
                </div>
            </div>
        
</section>


</main>

    <footer>
        <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Phone</h4>
                <p>7846262</p>
            </div>
    
            <div class="content-foo">
                <h4>Email</h4>
                <p>7846262</p>
            </div>
    
            <div class="content-foo">
                <h4>Location</h4>
                <p>7846262</p>
            </div>
        </div>
        <h2 class="titulo-final">&copy; Mariana-Pérez-Escalona| Diseñadora Frontend</h2>
    </footer>
    
</body>
</html>