<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grupos Parroquiales</title>

<!--Enlace a CSS-->
<link rel="stylesheet" href="../css/grupos.css">

<!--BOOTSTRAP-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>
<!--BOOTSTRAP-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>

<header>

    <nav>
        <a href="../index.html">Inicio</a>
        <a href="../intranet/catequesis.html">Catequesis</a>
       <!-- <a href="#">Instalaciones</a>
        <a href="#">Historia</a> -->
        <a href="../intranet/grupos.html">Grupos Parroquiales</a>
    </nav>


    <section class="textos-header">
        <h1>Alabando y Santificando</h1>
        <h2>Somos comunidad</h2>
    </section>

    <!--Onda descargada de internet-->
    <div class="wave">
        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M-5.41,68.39 C148.08,144.18 275.05,95.96 510.95,57.57 L500.00,149.60 L-0.00,149.60 Z"
                    style="stroke: none; fill:white;"></path>
            </svg></div>
    </div>


</header>

<main>
    <div class="container">
    
    <h2 class="titulo">Ven y Únetenos</h2>
    
        <div class="evento">
            <div class="foto">
                <img src="../img/1.png" alt="">
            </div>

            <div class="des_grupo"><h3>Legión de María</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae voluptatibus eos, tempora quos ratione qui eum atque maxime debitis!</p>
            </div>

        </div>
        <div class="evento">
            <div class="foto">
                <img src="../img/1.png" alt="">
            </div>
            <div class="des_grupo">
                <h3>Grupo CERS</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae voluptatibus eos, tempora quos ratione
                    qui eum atque maxime debitis!</p>
            </div>
        </div>
        <div class="evento">
            <div class="foto">
                <img src="../img/1.png" alt="">
            </div>
            <div class="des_grupo">
                <h3>Grupo de Semilleros</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae voluptatibus eos, tempora quos ratione
                    qui eum atque maxime debitis!</p>
            </div>
        </div>
        <div class="evento">
            <div class="foto">
                <img src="../img/1.png" alt="">
            </div>
            <div class="des_grupo">
                <h3>Grupo CAF</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae voluptatibus eos, tempora quos ratione
                    qui eum atque maxime debitis!</p>
            </div>
        </div>
        <div class="evento">
            <div class="foto">
                <img src="../img/1.png" alt="">
            </div>
            <div class="des_grupo">
                <h3>Adoración Nocturna</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae voluptatibus eos, tempora quos ratione
                    qui eum atque maxime debitis!</p>
            </div>
        </div>
        <div class="evento">
            <div class="foto">
                <img src="../img/1.png" alt="">
            </div>
            <div class="des_grupo">
                <h3>Ministros de Comunión</h3>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dicta recusandae voluptatibus eos, tempora quos ratione
                    qui eum atque maxime debitis!</p>
            </div>
        </div>
    </div>
</main>
    
    <footer>
        <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Phone</h4>
                <p>7846262</p>
            </div>
    
            <div class="content-foo">
                <h4>Email</h4>
                <p>7846262</p>
            </div>
    
            <div class="content-foo">
                <h4>Location</h4>
                <p>7846262</p>
            </div>
        </div>
        <h2 class="titulo-final">&copy; Mariana-Pérez-Escalona| Diseñadora Frontend</h2>
    </footer>

</body>
</html>