<!-- Estilos Generales -->
<style>
*{
    padding:0;
    margin:0;
    box-sizing:border-box;
}

body{
font-family: 'Lora', serif;
}

.contenedor{
    padding: 60px; /*Establece el área de relleno en los cuatro lados de un elemento a la vez*/    
}

.titulo{
    color:black;
    font-size:45px;
    text-align: center;
    margin-bottom: 60px;
}

header {
    width: 100%;
    height: 600px;
    
        background: #DA4453;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, hsla(317, 61%, 33%, 0.705), hsla(354, 67%, 56%, 0.705));
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, hsla(317, 61%, 33%, 0.705), hsla(354, 67%, 56%, 0.705)),            
            url(../img/ilus1.png);
        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background-size: cover;
    background-attachment: fixed;
    position: relative;
}


nav{
    text-align: right;
    padding: 30px 50px 0 0;
}

nav > a{
    color:aliceblue;
    font-weight: 300; /*Hará la letra más ligera*/
    text-decoration: none; /*Le quita el subrayado*/
    margin-right: 15px; /*Le da un espaciado*/
    text-align: center;
    justify-content: center;
    font-size: 150%;
        
}

nav>a:hover {   
    text-decoration: underline;
    /*Si el cursor esta encima de los enlaces se subrayan*/
    }

.wave{
    position: absolute;
    bottom: -1%; /*Indica que tan pegado esta el objeto del contenedor*/
    width: 100%;    
}

header .textos-header{
    display:flex;
    height: 430px; /*Altura a la que queda el texto*/
    width: 100%;
    align-items: left; /*Organiza al texto en el eje x*/
    justify-content:center ; /*Organiza el texto en el eje y*/
    flex-direction: column; /*Permite a los renglones ponerse unos debajo de otros*/
    text-align: center;

}

.textos-header h1{
    font-family: 'Lora',serif;
    font-size: 50px;
    color:white;
    }

.textos-header h2{
    font-family: 'Lora', serif;
    font-size: 30px;
    font-weight: 300; /*Anchura de la fuente*/
    color:white;
}

</style>



<!--SECCIÓN DEL ENCABEZADO PARA TODAS LAS PÁGINAS-->

    <link rel="shortcut icon" href="img/ilustracion1.png" type="image/x-icon">

    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>

 <!--CDN jQuery-->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
        
 
 <!--BOOTSTRAP-->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">



<body>

<!--BOOTSTRAP-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>

<header>
                
    <nav>
        <a href="index.php" style="display: none;">Inicio</a>
        <a href="intranet/catequesis.php" style="">Catequesis</a>
        <a href="intranet/grupos.php" style="">Grupos Parroquiales</a>
    </nav>

<!--     Menu para que se escojan las frases de cada página -->

<section class="textos-header" style="display: <?php echo ($pagina_actual == 'inicio') ? 'display' : 'none'; ?>;">
    <h1>¿Quién como Dios?</h1>
    <h2>Nadie como Dios</h2>
</section>

<section class="textos-header" style="display: <?php echo ($pagina_actual == 'catequesis') ? 'display' : 'none'; ?>;">
    <h1>Libres para liberar</h1>
    <h2>No hay mejor maestro que Jesús</h2>
</section>

<section class="textos-header" style="display: <?php echo ($pagina_actual == 'grupos') ? 'display' : 'none'; ?>;">
    <h1>Alabando y santificando</h1>
    <h2>Somos Comunidad</h2>
</section>

    <!--Onda descargada de internet-->
    <div class="wave">
<!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

<div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
        style="height: 100%; width: 100%;">
        <path d="M-5.41,68.39 C148.08,144.18 275.05,95.96 510.95,57.57 L500.00,149.60 L-0.00,149.60 Z"
            style="stroke: none; fill:white;"></path>
    </svg></div>
</div>
