 
 <!--SECCIÓN DEL ENCABEZADO PARA TODAS LAS PÁGINAS-->
 
 <!--BOOTSTRAP-->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <link rel="stylesheet" href="css/estilos.css">
    <link rel="shortcut icon" href="img/ilustracion1.png" type="image/x-icon">

    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>

    <!--CDN jQuery-->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>

</head>
<body>

<!--BOOTSTRAP-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
    crossorigin="anonymous"></script>

    <header>
                
        <nav>
            <a href="index.html">Inicio</a>
            <a href="intranet/catequesis.html">Catequesis</a>
            <!--<a href="#">Instalaciones</a>
            <a href="#">Historia</a> -->           
            <a href="intranet/grupos.html">Grupos Parroquiales</a>
        </nav>


    <section class="textos-header">
        <h1>¿Quién como Dios?</h1>
        <h2>Nadie como Dios</h2>
    </section>

    <!--Onda descargada de internet-->
    <div class="wave">
<!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

<div style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
        style="height: 100%; width: 100%;">
        <path d="M-5.41,68.39 C148.08,144.18 275.05,95.96 510.95,57.57 L500.00,149.60 L-0.00,149.60 Z"
            style="stroke: none; fill:white;"></path>
    </svg></div>
    </div>


    </header>
